wandb_version: 1

learning_rate:
  desc: null
  value: 3.0e-05
epochs:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.17.1
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718382255
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.11.6
      5: 0.17.1
      6: 4.41.2
      8:
      - 5
      13: linux-x86_64
