wandb_version: 1

learning_rate:
  desc: null
  value: 5.0e-05
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.0
    framework: huggingface
    huggingface_version: 4.26.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682852614.7683
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.8.10
      5: 0.15.0
      6: 4.26.1
      8:
      - 5
