#!/usr/bin/env python3
# -*- coding: utf-8 -*-

__description__ = (" search terms for potential wikipedia articles compiled by me and by ChatGPT3 asking for terms from the "
                   "fields life sciences, antrophosophic medicine, homeopathy, internal medicine, Cardiological Medicine, "
                   "Visceral Surgery, Esoteric, nutrition, pregnancy, tobacco  ")
__author__ = "Eva Seidlmayer <seidlmayer@zbmed.de>"
__copyright__ = "2021 by Eva Seidlmayer"
__license__ = "ISC license"
__email__ = "seidlmayer@zbmed.de"
__version__ = "1 "


import wikipedia
wikipedia.set_lang('en')
import argparse
import pandas as pd
import re

argsparser = argparse.ArgumentParser()
args = argsparser.parse_args()


# topic list compiled by ChatGPT3
topics = ["Biodiversity", "Ecosystem", "Habitat", "Conservation", "Sustainable development", "Ecological succession",
          "Ecological footprint", "Ecological niche", "Ecological services", "Ecological functions", "Ecological restoration",
          "Ecological balance", "Ecological resilience", "Ecological diversity", "Ecological system", "Ecological interactions",
          "Ecological corridors", "Ecological monitoring", "Ecological stability", "Ecological risk assessment", "Ecological modelling",
          "Ecological genetics", "Ecological footprint", "DNA", "RNA", "proteins", "gene expression", "genetic engineering",
          "cells", "genetics", "evolution", "ecology", "biochemistry", "microbiology", "psychiatry", "biotechnology",
          "biophysics", "neuroscience", "cancer", "immunology", "epidemiology", "endocrinology", "virology", "botany",
          "zoology", "physiology", "pharmacology", "toxicology", "psychiatry", "biostatistics", "ecology", "biochemistry",
          "psychiatry", "psychiatry", "genetic engineering", "Cloning", "Recombinant DNA", "Bioprocessing", "Bioprinting",
          "Bioreactor", "Metabolic engineering", "Synthetic biology", "Biomanufacturing", "Immunotechnology",
          "Biopharmaceuticals", "Stem cells", "Tissue engineering", "Biomaterials", "Microbial biotechnology",
          "Biocatalysis", "Biopesticides", "Bioremediation", "Biofuels", "Bioseparation", "Biocomputing",
          "Biomedical engineering", "Biosensors", "Biomarkers", "Bioprospecting", "Bioplastics", "Biodegradable materials",
          "Biocatalysts", "Bioprocess control", "Bioprocess scale-up", "Bioprocess design", "Bioprocess modeling",
          "Bioprocess validation", "Bioprocess optimization", "Bioprocess monitoring", "Bioprocess safety",
          "Bioprocess regulations", "Bioprocess patenting", "Bioprocess commercialization", "Bioprocess investment",
          "Immune system", "Antigen", "Antibody", "T cells", "B cells", "Immunoglobulins", "MHC molecules", "Cytokines",
          "Lymphocytes", "Immunological memory", "Immune response", "Autoimmunity", "Allergy", "Immunodeficiency",
          "Immune tolerance", "Vaccines", "Immune surveillance", "Immune cell activation", "Immune cell differentiation",
          "Immune cell migration", "Immune cell signaling", "Immune cell apoptosis", "Immune cell senescence",
          "Immune cell regeneration", "Immune cell aging", "Immune cell metabolism", "Immune cell plasticity",
          "Immune cell interactions", "Immune cell metabolism", "Immune cell plasticity", "Immune cell interactions",
          "Immune cell education", "Immune cell activation", "Immune cell differentiation", "Immune cell migration",
          "Immune cell signaling", "Immune cell apoptosis", "Immune cell senescence", "Immune cell regeneration",
          "Immune cell aging", "Immune cell metabolism", "Immune cell plasticity", "Immune cell interactions",
          "Immune cell education", "Immune cell activation", "Immune cell differentiation", "Immune cell migration",
          "Immune cell signaling", "Immune cell apoptosis", "Immune cell senescence", "Mental health", "Depression",
          "Anxiety", "Psychotherapy", "Psychiatrist", "Medication", "Schizophrenia", "Bipolar disorder",
          "Personality disorder", "Post-traumatic stress disorder", "Addiction", "Eating disorder",
          "Obsessive-compulsive disorder", "Attention deficit hyperactivity disorder", "Autism spectrum disorder",
          "Dementia", "Mood disorder", "Substance abuse", "Trauma", "Stress", "Grief", "Sleep disorder",
          "Psychoanalysis", "Cognitive-behavioral therapy", "Dialectical behavior therapy", "Interpersonal therapy",
          "Family therapy", "Group therapy", "Art therapy", "Music therapy", "Animal assisted therapy", "Mindfulness",
          "Neuropsychiatry", "Forensic psychiatry", "Child psychiatry", "Geriatric psychiatry", "Clinical neuroscience",
          "Neuroimaging", "Neuropsychology", "Neuropharmacology", "Social psychiatry", "Community psychiatry",
          "Cultural psychiatry", "Global mental health", "Public mental health", "Mental health policy", "Mental health reform",
          "Mental health stigma", "Mental health advocacy", "Anatomy", "Physiology", "Pathology", "Microbiology",
          "Immunology", "Pharmacology", "Therapeutics", "Surgery", "Obstetrics", "Gynecology", "Pediatrics", "Geriatrics",
          "Oncology", "Cardiology", "Endocrinology", "Gastroenterology", "Hematology", "Infectious disease", "Nephrology",
          "Neurology", "Ophthalmology", "Orthopedics", "Otolaryngology", "Psychiatry", "Pulmonology", "Radiology",
          "Rheumatology", "Urology", "Anesthesiology", "Dermatology", "Emergency medicine", "Family medicine",
          "Internal medicine", "Physical medicine", "Sports medicine", "Clinical research", "Clinical trials",
          "Epidemiology", "Public health", "Global health", "Health policy", "Healthcare reform", "Medical ethics",
          "Medical education", "Medical technology", "Medical informatics", "Medical devices", "Telemedicine",
          "Medical imaging", "Medical robots", "Medical artificial intelligence", "Vitamins", "Minerals", "Herbs",
          "Probiotics", "Enzymes", "Amino acids", "Omega-3", "Antioxidants", "Fiber", "Phytochemicals", "Food-based supplements",
          "Herbal supplements", "Nutraceuticals", "Dietary supplements", "Functional food", "Food fortification",
          "Food enrichment", "Food ingredients", "Food additives", "Food labeling", "Food safety", "Food regulations",
          "Food standards", "Food science", "Food technology", "Food processing", "Food packaging", "Food preservation",
          "Food microbiology", "Food chemistry", "Food engineering", "Food biotechnology", "Food sustainability",
          "Food security", "Food waste", "Food traceability", "Food culture", "Food history", "Food anthropology",
          "Food trends", "Food marketing", "Food advertising", "Food literacy", "Food education", "Elder care",
          "Child care", "Disability care", "Mental health care", "Home care", "Residential care", "Hospice care",
          "Palliative care", "Long-term care", "End-of-life care", "Assisted living", "Nursing care", "Social care",
          "In-home care", "Community care", "Care coordination", "Care management", "Care planning", "Care assessment",
          "Care delivery", "Caregiving", "Care work", "Care work force", "Care work policies", "Care work rights",
          "Care work benefits", "Care work training", "Care work education", "Care work diversity", "Care work ethics",
          "Care work standards", "Care work regulations", "Care work reform", "Care work advocacy", "Care work research",
          "Care work innovation", "Care work technology", "Care work telecare", "Care work robots", "Care work artificial intelligence",
          "Plants", "Photosynthesis", "Taxonomy", "Ecology", "Phytochemistry", "Phylogenetics", "Genetics", "Evolution",
          "Morphology", "Anatomy", "Physiology", "Palynology", "Mycology", "Phycology", "Bryology", "Pteridology", "Systematics",
          "Dendrology", "Ethnobotany", "Phytopharmacology", "Plant breeding", "Plant biotechnology", "Plant pathology",
          "Plant physiology", "Plant ecology", "Plant physiology", "Plant physiology", "Plant physiology", "Plant psychiatry",
          "Plant physiology", "Plant psychiatry", "Plant physiology", "Plant psychiatry", "Plant psychiatry", "Plant psychiatry",
          "Plant psychiatry", "Plant psychiatry", "Plant psychiatry", "Plant psychiatry", "Plant psychiatry", "Plant psychiatry",
          "Plant psychiatry", "Plant psychiatry", "Plant psychiatry", "Plant psychiatry", "Plant psychiatry", "Plant psychiatry",
          "Plant psychiatry", "Plant psychiatry", "Microorganisms", "Bacteria", "Viruses", "Fungi", "Protozoa", "Algae",
          "Microbial ecology", "Microbial diversity", "Microbial physiology", "Microbial genetics", "Microbial physiology",
          "Microbial physiology", "Microbial physiology", "Microbial physiology", "Microbial physiology", "Microbial psychiatry",
          "Microbial physiology", "Microbial psychiatry", "Microbial physiology", "Microbial psychiatry", "Microbial physiology",
          "Microbial psychiatry", "Microbial physiology", "Microbial psychiatry", "Nutrients", "Diet", "Metabolism",
          "Healthy eating", "Weight management", "Food groups", "Macronutrients", "Micronutrients", "Vitamins", "Minerals",
          "Amino acids", "Fatty acids", "Carbohydrates", "Proteins", "Fiber", "Water", "Energy balance", "Nutrition assessment",
          "Nutrition education", "Nutrition intervention", "Nutrition research", "Nutrition epidemiology", "Nutrition policy",
          "Nutrition regulations", "Nutrition standards", "Nutrition labeling", "Nutrition claims", "Nutrition and disease",
          "Nutrition and aging", "Nutrition and fitness", "Nutrition and pregnancy", "Nutrition and lactation",
          "Nutrition and childhood", "Nutrition and adolescence", "Nutrition and older adults", "Nutrition and public health",
          "Nutrition and sustainability", "Nutrition and food security", "Nutrition and global health", "Nutrition and food industry",
          "Nutrition and food technology", "Nutrition and food science", "Nutrition and food systems", "Crops", "Soils",
          "Fertilizers", "Pesticides", "Irrigation", "Genetics", "Plant breeding", "Agronomy", "Horticulture", "Entomology",
          "Pathology", "Weed science", "Soil science", "Water management", "Agricultural engineering", "Agricultural economics",
          "Agricultural extension", "Agricultural policy", "Agricultural sustainability", "Agricultural productivity",
          "Agricultural biotechnology", "Agricultural mechanization", "Agricultural waste management", "Agricultural conservation",
          "Agricultural ecology", "Agricultural meteorology", "Agricultural climatology", "Agricultural remote sensing",
          "Agricultural statistics", "Agricultural education", "Agricultural research", "Agricultural development",
          "Agricultural industry", "Agricultural market", "Agricultural trade", "Agricultural innovation", "Agricultural technology",
          "Agricultural robotics", "Agricultural artificial intelligence", "Agricultural precision", "Agricultural genomics",
          "SARS-CoV-2", "Coronavirus", "COVID-19", "Pandemic", "Virus", "Infection", "Symptoms", "Transmission", "Immunity",
          "Vaccines", "Treatment", "Mortality", "Masks", "Social distancing", "Quarantine", "Isolation", "Contact tracing",
          "Testing", "Lockdown", "Clinical trials", "Epidemiology", "Virology", "Immunology", "Public health", "Healthcare system",
          "Economic impact", "Mental health", "Remote work", "Education", "Travel restrictions", "Vaccine hesitancy",
          "Vaccine distribution", "Vaccine efficacy", "Vaccine safety", "Variants", "Mutation", "Antiviral drugs",
          "Therapeutic monoclonal antibodies", "Pneumonia", "ARDS", "Rehospitalization", "Mortality", "Health equity",
          "Global response", "Pandemic preparedness","Oncology", "Cancer cells", "Cancer biology", "Cancer genetics",
          "Cancer epidemiology", "Cancer screening", "Cancer diagnosis", "Cancer treatment", "Cancer surgery",
          "Cancer radiation therapy", "Cancer chemotherapy", "Cancer immunotherapy", "Cancer targeted therapy",
          "Cancer stem cells", "Cancer biomarkers", "Cancer prognosis", "Cancer survival", "Cancer prevention",
          "Cancer epidemiology", "Cancer genetics", "Cancer immunology", "Cancer pathology", "Cancer pharmacology",
          "Cancer statistics", "Cancer research", "Cancer clinical trials", "Cancer drug development", "Cancer nanotechnology",
          "Cancer informatics", "Cancer genomics", "Cancer epigenetics", "Cancer proteomics", "Cancer metabolomics",
          "Cancer systems biology", "Cancer precision medicine", "Cancer survivorship", "Cancer palliative care",
          "Cancer advocacy", "Anatomy", "Head and Neck", "Thorax", "Abdomen", "Pelvis", "Upper Limb", "Lower Limb",
          "Biochemistry", "Biostatistics", "Embryology", "Epidemiology", "Genetics", "Immunology", "Investigative Pathology",
          "Medical Statistics", "Medical Informatics", "Microbiology (includes Bacteriology)", "Parasitology", "Virology",
          "Neuroscience", "Cytology", "Toxicology", "Histology", "Histopathology", "Pathophysiology", "Pharmacology",
          "Psychiatry", "Bioethics", "Medicine", "Emergency Medicine", "General Practitioner", "Internal Medicine",
          "Cardiology", "Critical Care Medicine", "Endocrinology", "Gastroenterology", "Hepatology", "Geriatric Medicine",
          "Hematology", "Infectious Diseases", "AIDS Medicine", "Genito-Urinary Medicine", "Nephrology", "Oncology", "Primary Care",
          "Pulmonology", "Rheumatology", "Medical Genetics", "Neurology", "Occupational Medicine", "Anesthesiology", "Pain Medicine",
          "Dentistry", "Dental Public Health", "Endodontics", "Oral and Maxillofacial Pathology", "Oral and Maxillofacial Surgery",
          "Oral Medicine", "Oral Radiology", "Orthodontics", "Pediatric Dentistry", "Periodontics", "Prosthodontics",
          "Fixed Prosthodontics", "Removable Prosthodontics", "Dermatology", "Obstetrics & Gynecology", "Gynecology",
          "Gynecologic Surgery", "Gynecologic Oncology", "Maternal/Fetal Medicine", "Obstetrics", "Reproductive Endocrinology and Fertility",
          "Ophthalmology", "Cataract Surgery", "Oculoplastic Surgery", "Refractive Surgery", "Vitreo-Retinal Surgery",
          "Pathology", "Anatomic Pathology", "Autopsy", "Cytopathology", "Forensic Pathology", "Molecular Pathology",
          "Surgical Pathology", "Clinical Pathology", "Clinical Chemistry", "Cytology", "Hematopathology",
          "Medical Microbiology", "Transfusion Medicine", "Pediatrics", "Adolescent Medicine", "Child Abuse Medicine",
          "Developmental Pediatrics", "Neonatology", "Pediatric Cardiology", "Pediatric Critical Care", "Pediatric Endocrinology",
          "Physicians", "Physician Assistants", "Nurses", "Nurse Practitioners", "Nurse Specialists", "Nurse Anaesthetists",
          "Nurse Midwives", "Dietitians", "Midwives", "Therapists", "Physical Therapists", "Respiratory Therapists",
          "Occupational Therapists", "Speech Therapists", "Allied Health Care Professionals", "Independent Practitioners",
          "Dentists", "Podiatrists", "Audiologists", "Optometrists", "Dependent Practitioners", "Physical Therapists",
          "Occupational Therapists", "Diagnostic Procedures", "EMG", "Doppler", "Cardiology Diagnostic Procedures",
          "Cardiac Catheterization", "Echocardiogram", "Pericardiocentesis", "EKG", "12-lead", "24 Hour", "Stress Tests",
          "Stress Echo", "Stress EKG", "Pulmonary Diagnostic Procedures", "Lung Function Studies", "Thoracocentesis",
          "Pleural Biopsy", "Bronchoscopy", "Other", "Joint Aspiration", "Peritoneal Lavage", "Bone Marrow Aspiration",
          "Gastroenterological Diagnostic Procedures", "Colonoscopy +/- Biopsy", "Sigmoidoscopy +/- Biopsy",
          "Proctosigmoidoscopy", "Anoscopy", "ERCP", "MRCP", "Esophagogastroduodenoscopy (Upper Endoscopy)", "Endoscopic Ultrasound",
          "Capsule Enteroscopy", "Liver Biopsy", "Esophageal Manometry", "24 Hour pH Monitoring", "Gastric Analysis",
          "Pancreatic Function Tests", "Radiologic Diagnostic Procedures", "Ultrasound", "X-ray", "CT scan", "Spiral CT",
          "Contrast CT", "MRI Scan", "Nuclear Medicine", "Laboratory Procedures", "Blood Tests", "Blood Chemistry",
          "Serum Sodium", "Serum Potassium", "Serum Chloride", "Serum Bicarbonate", "Blood Urea Nitrogen", "Blood Glucose",
          "Serum Creatinine", "Cerebrospinal Fluid Tests", "Cultures", "Viral Culture", "Bacterial Culture", "Fungal Culture",
          "Serology", "Brain Tests", "PET", "EEG", "Dermatology", "Cutaneous conditions", "Acneiform eruptions",
          "Autoinflammatory syndromes", "Chronic blistering cutaneous conditions", "Conditions of the mucous membranes",
          "Conditions of the skin appendages", "Conditions of the subcutaneous fat", "Connective tissue diseases",
          "Abnormalities of dermal fibrous and elastic tissue", "Cutaneous congenital anomalies", "Dermal and subcutaneous growths",
          "Dermatitis", "Atopic dermatitis", "Contact dermatitis", "Eczeama", "Pustular dermatitis", "Seborrheic dermatitis",
          "Disturbances of human pigmentation", "Drug eruptions", "Endocrine-related cutaneous conditions",
          "Eosinophilic cutaneous conditions", "Epidermal nevi, neoplasms, cysts", "Erythemas", "Genodermatoses",
          "Infection-related cutaneous conditions", "Bacterium-related cutaneous conditions",
          "Mycobacterium-related cutaneous conditions", "Mycosis-related cutaneous conditions",
          "Parasitic infestations, stings, and bites of the skin", "Virus-related cutaneous conditions", "Lichenoid eruptions",
          "Lymphoid-related cutaneous conditions", "Melanocytic nevi and neoplasms", "Melanoma",
          "Monocyte- and macrophage-related cutaneous conditions", "Mucinoses", "Neurocutaneous conditions",
          "Noninfectious immunodeficiency-related cutaneous conditions", "Papulosquamous hyperkeratotic cutaneous conditions",
          "Palmoplantar keratodermas", "Pregnancy-related cutaneous conditions", "Pruritic skin conditions", "Psoriasis",
          "Reactive neutrophilic cutaneous conditions", "Recalcitrant palmoplantar eruptions", "Skin conditions resulting from errors in metabolism",
          "Skin conditions resulting from physical factors", "Ionizing radiation-induced cutaneous conditions",
          "Urticaria and angioedema", "Vascular-related cutaneous conditions", "Dermatologic drugs", "Anti-acne preparations",
          "Antibiotics and chemotherapeutics for dermatologic use", "Antifungals for dermatologic use", "Antipruritics",
          "Antipsoriatics", "Antiseptics and disinfectants", "Dermatologic preparations of corticosteroids",
          "Emollients and protectives", "Medicated dressings", "Preparations for treatment of wounds and ulcers",
          "Dermatologic procedures and surgery", "Dermatologic signs", "Dermatologic societies", "Dermatologic terminology",
          "Dermatologists", "Dermatology journals", "Hair", "Hair anatomy", "Hair psychiatry", "Nails", "Nail anatomy",
          "Nail psychiatry", "Skin", "Skin anatomy", "Skin psychiatry", "Homeopathy", "Alternative Medicine", "Holistic Healing",
          "Remedies", "Dilution", "Potentization", "Similia Similibus Curentur", "Law of Similars", "Vital Force", "Materia Medica",
          "Repertory", "Constitutional Treatment", "Individualization", "Succussion", "High Dilutions", "Low Dilutions",
          "Homeopathic Pharmacopeia", "Chronic Diseases", "Acute Conditions", "Single Remedy", "Complex Remedy", "Nosodes",
          "Isopathy", "Proving", "Aggravation", "Hering's Law", "Case Taking", "Potency", "LM Potencies", "C Potencies",
          "X Potencies", "Q Potencies", "Water Memory", "Bioresonance", "Vitalism", "Energy Medicine", "Chronic Miasms",
          "Psora", "Sycosis", "Syphilis", "Tubercular Miasm", "Law of Cure", "Sensation Method", "Organon of Medicine",
          "Samuel Hahnemann", "Homeopathic Aggravation", "Homeopathic Repertories", "Kent's Repertory", "Boenninghausen's Repertory",
          "Murphy's Repertory", "Synthesis Repertory", "Boger's Repertory", "Miasms", "Constitutional Types", "Mental Symptoms",
          "Emotional Symptoms", "Physical Symptoms", "Homeopathic First Aid", "Homeopathic Schools", "Homeopathic Colleges",
          "Homeopathic Associations", "Homeopathic Journals", "Homeopathic Research", "Homeopathic Clinical Trials",
          "Homeopathic Success Stories", "Homeopathic Philosophy", "Homeopathic Books", "Homeopathic Education", "Homeopathic Diagnosis",
          "Homeopathic Techniques", "Homeopathic Approach", "Homeopathic Herbs", "Homeopathic Minerals", "Homeopathic Pediatrics",
          "Homeopathic Dermatology", "Homeopathic Psychiatry", "Homeopathic Veterinary Medicine", "Homeopathic Repertorization",
          "Homeopathic Software", "Homeopathic Materia Medica", "Homeopathic Pharmacy", "Homeopathic Manufacturing", "Homeopathic History",
          "Homeopathic Pioneers", "Homeopathic Masters", "Homeopathic Remedies", "Homeopathic Treatment Modalities", "Homeopathic Dosage",
          "Homeopathic Research", "Homeopathic Evidence", "Homeopathic Remedial Measures", "Homeopathic Learning", "Homeopathic Resources",
          "Homeopathic Workshops", "Homeopathic Seminars", "Homeopathic Conferences", "Homeopathic Training", "Homeopathic Mentorship",
          "Homeopathic Ethics", "Homeopathic Professionalism", "Homeopathic Regulation", "Homeopathic Safety", "Homeopathic Healing Process",
          "Homeopathic Holism", "Homeopathic Integration", "Homeopathic Mind-Body Connection", "Homeopathic Vitality", "Homeopathic Balance",
          "Homeopathic Wellness", "Homeopathic Nutritional Support", "Homeopathic Detoxification", "Homeopathic Lifestyle",
          "Homeopathic Mindfulness", "Homeopathic Spirituality", "Homeopathic Energy", "Homeopathic Wellbeing", "Homeopathic Harmony",
          "Homeopathic Transformation", "Homeopathic Awakening", "Homeopathic Resilience", "Homeopathic Empowerment", "Homeopathic Empathy",
          "Homeopathic Compassion", "Homeopathic Nurturing", "Homeopathic Self-discovery", "Homeopathic Growth", "Homeopathic Wholeness",
          "Homeopathic Self-awareness", "Homeopathic Personal Development", "Homeopathic Energy Healing", "Homeopathic Self-healing",
          "Homeopathic Mind-Body Healing", "Homeopathic Emotional Healing", "Homeopathic Physical Healing", "Homeopathic Vibrational Healing",
          "Homeopathic Subtle Healing", "Homeopathic Inner Healing", "Homeopathic Natural Healing", "Homeopathic Inner Wisdom",
          "Homeopathic Inner Balance", "Homeopathic Inner Peace", "Homeopathic Inner Harmony", "Homeopathic Inner Connection",
          "Homeopathic Inner Alignment", "Homeopathic Inner Transformation", "Homeopathic Inner Resilience", "Homeopathic Inner Empowerment",
          "Homeopathic Inner Growth", "Homeopathic Inner Wellness", "Homeopathic Inner Healing Process", "Homeopathic Inner Journey",
          "Homeopathic Inner Awakening", "Homeopathic Inner Discovery", "Homeopathic Inner Enlightenment", "Homeopathic Inner Evolution",
          "Homeopathic Inner Fulfillment", "Homeopathic Inner Joy", "Homeopathic Inner Love", "Homeopathic Inner Light",
          "Homeopathic Inner Radiance",
          "Anthroposophic Medicine", "Rudolf Steiner", "Integrated Medicine", "Holistic Healing", "Spiritual Science",
          "Anthroposophy", "Biodynamic Agriculture", "Curative Eurythmy", "Artistic Therapies", "Homeopathic Remedies",
          "Mistletoe Therapy", "Rhythmic Massage", "External Applications", "Fomentations", "Compresses", "Oil Dispersion Baths",
          "Mist Applications", "Lifestyle Recommendations", "Natural Substances", "Inner Balance", "Spiritual Insights",
          "Individualized Treatment", "Threefold Human Being", "Physical Body", "Soul or Emotional Body", "Spiritual or Ego Body",
          "Dynamic Interactions", "Holistic Approach", "Salutogenesis", "Health Promotion", "Disease Prevention", "Natural Therapies",
          "Nutritional Counseling", "Mental Health", "Anthroposophic Psychology", "Counseling", "Psychotherapy", "Meditative Practices",
          "Healing Environment", "Biographical Counseling", "Eurythmy Therapy", "Art Therapy", "Music Therapy", "Rhythmical Massage Therapy",
          "Spacial Dynamics", "Hydrotherapy", "Clay Applications", "Sage Therapies", "Embryology", "Embryonic Recapitulation",
          "Individualized Medicine", "Subtle Forces", "Astral Body", "Etheric Body", "Life Forces", "Subtle Energies", "Pharmacology",
          "Herbal Medicines", "Mineral Medicines", "Animal-derived Medicines", "Therapeutic Movement", "Harmonizing Therapies",
          "Natural Healing", "Holistic Assessment", "Mind-Body-Spirit Connection", "Anthroposophic Nursing", "Therapeutic Speech",
          "Elemental Medicines", "Inhalations", "Soul Exercises", "Therapeutic Eurythmy", "Phytotherapy", "Anthroposophic Medicine Training",
          "Integrative Health", "Alternative Therapies", "Anthroposophic Pharmacies", "Eurythmy Movement Therapy", "Individualized Care",
          "Spiritual Well-being", "Vitality", "Self-awareness", "Self-healing", "Individual Potential", "Harmonious Balance",
          "Anthroposophic Lifestyle", "Spiritual Growth", "Complementary Medicine", "Anthroposophic Therapeutic Education",
          "Nature Therapies", "Natural Substances", "Anthroposophic Dietary Recommendations", "Comprehensive Healing",
          "Steiner's Philosophy of Medicine", "Complementary and Alternative Medicine", "Energetic Healing", "Holistic Therapies",
          "Spiritual Healing", "Eco-friendly Practices", "Sustainable Living", "Mindfulness", "Therapeutic Relationships",
          "Anthroposophic Health Practitioners", "Holistic Counseling", "Spiritual Insights", "Mind-Body Balance", "Anthroposophic Research",
          "Multidimensional Healing", "Wholeness", "Anthroposophic Medicine Organizations", "Anthroposophic Lifestyle Choices",
          "Spiritual Wellbeing", "Subtle Healing Modalities", "Biographical Work", "Anthroposophic Medicine Approach", "Harmonious Living",
          "Anthroposophic Psychotherapy", "Anthroposophic Dietary Guidelines", "Energetic Body", "Natural Therapeutics",
          "Comprehensive Care", "Harmonizing Energies", "Holistic Therapeutic Methods", "Inner Healing Wisdom", "Anthroposophic Principles",
          "Spiritual Insights", "Anthroposophic Health Practices", "Rhythmic Breathing Exercises", "Subtle Healing Approaches",
          "Anthroposophic Spiritual Philosophy", "Anthroposophic Psychology", "Mind-Body Connection", "Anthroposophic Healthcare",
          "Individualized Therapies", "Internal Medicine", "Medical Specialty", "Adult Medicine", "Physician", "Doctor",
          "Diagnosis", "Treatment", "Prevention", "Disease Management", "Medical Consultation", "Primary Care", "Specialist",
          "Physical Examination", "Medical History", "Laboratory Tests", "Diagnostic Imaging", "Medical Procedures", "Health Promotion",
          "Chronic Diseases", "Acute Illnesses", "Healthcare", "Patient Care", "Internal Organs",
          "Cardiovascular System", "Respiratory System", "Digestive System", "Endocrine System", "Nervous System", "Renal System",
          "Musculoskeletal System", "Hematology", "Infectious Diseases", "Autoimmune Diseases", "Rheumatology", "Gastroenterology",
          "Pulmonology", "Cardiology", "Nephrology", "Endocrinology", "Neurology", "Geriatric Medicine", "Hematology", "Oncology",
          "Allergy and Immunology", "Critical Care Medicine", "Hepatology", "Inflammatory Diseases", "Metabolic Disorders",
          "Pulmonary Diseases", "Renal Disorders", "Cardiovascular Disorders", "Gastrointestinal Disorders", "Liver Diseases",
          "Diabetes", "Thyroid Disorders", "Hypertension", "Hyperlipidemia", "Heart Failure", "Asthma", "Chronic Obstructive Pulmonary Disease (COPD)",
          "Peptic Ulcer Disease", "Inflammatory Bowel Disease", "Kidney Diseases", "Stroke", "Seizures", "Dementia", "Osteoporosis",
          "Anemia", "Leukemia", "Lymphoma", "Gastroesophageal Reflux Disease (GERD)", "Hepatitis", "Pancreatitis", "Thrombosis",
          "Hypothyroidism", "Hyperthyroidism", "Obesity", "Cancer", "Vascular Diseases", "Arthritis", "Bronchitis", "Pneumonia",
          "Urinary Tract Infections", "Hypertensive Heart Disease", "Atrial Fibrillation", "Myocardial Infarction", "Coronary Artery Disease",
          "Diabetic Nephropathy", "Parkinson's Disease", "Alzheimer's Disease", "Celiac Disease", "Crohn's Disease", "Ulcerative Colitis",
          "Nephrolithiasis", "Multiple Myeloma", "Non-Hodgkin Lymphoma", "Gastrointestinal Bleeding", "Gallbladder Disease",
          "Hemochromatosis", "Hemophilia", "Cushing's Syndrome", "Addison's Disease", "Graves' Disease", "Diabetic Retinopathy",
          "Thyroid Nodules", "Hypertensive Emergency", "Cardiac Arrhythmias", "Aortic Aneurysm", "Acute Respiratory Distress Syndrome (ARDS)",
          "Chronic Kidney Disease", "Cerebrovascular Disease", "Pulmonary Embolism", "Epilepsy", "Multiple Sclerosis", "Cirrhosis",
          "Liver Cancer", "Gastroenteritis", "Hemorrhoids", "Sepsis", "Acute Pancreatitis", "Deep Vein Thrombosis", "Hyperparathyroidism",
          "Polycystic Ovary Syndrome", "Lupus", "Rheumatoid Arthritis", "Type 1 Diabetes", "Type 2 Diabetes", "Hypoglycemia",
          "Obstructive Sleep Apnea", "Lung Cancer", "Colorectal Cancer", "Breast Cancer", "Prostate Cancer", "Lung Infections",
          "Tuberculosis", "Influenza", "Celiac Disease", "Gastroesophageal Reflux Disease (GERD)", "Irritable Bowel Syndrome (IBS)",
          "Lupus", "Autoimmune Hepatitis", "Crohn's Disease", "Gout", "Rheumatoid Arthritis", "Polymyalgia Rheumatica", "Lyme Disease",
          "Eosinophilic Esophagitis", "Amyloidosis", "Sarcoidosis", "Vasculitis", "Cushing's Syndrome", "Pheochromocytoma", "Thyroid Cancer",
          "Adrenal Disorders", "Addison's Disease", "Cushing's Syndrome", "Acromegaly", "Pituitary Tumors", "Gastrointestinal Bleeding",
          "Cirrhosis", "Chronic Hepatitis", "Liver Transplantation", "Ascites", "Cholangiocarcinoma", "Kidney Stones", "Glomerular Diseases",
          "Polycystic Kidney Disease", "Nephrotic Syndrome", "Pyelonephritis", "Interstitial Nephritis", "Hematuria", "Hemodialysis",
          "Chronic Obstructive Pulmonary Disease (COPD)", "Asthma", "Pulmonary Hypertension", "Lung Transplantation", "Interstitial Lung Disease",
          "Pleural Effusion", "Bronchiectasis", "Pneumothorax", "Emphysema", "Lung Cancer", "Chronic Respiratory Failure", "Pulmonary Embolism",
          "Coronary Artery Disease", "Heart Failure", "Hypertension", "Arrhythmias", "Aortic Valve Disorders", "Mitral Valve Disorders",
          "Cardiomyopathy", "Congenital Heart Disease", "Pericarditis", "Endocarditis", "Angina", "Atrial Fibrillation", "Myocardial Infarction",
          "Stroke", "Deep Vein Thrombosis", "Pulmonary Embolism", "Hypertrophic Cardiomyopathy", "Acute Respiratory Distress Syndrome (ARDS)",
          "Sepsis", "Septic Shock", "Hypertensive Crisis", "Acute Kidney Injury", "Acute Myocardial Infarction", "Acute Coronary Syndrome",
          "Acute Pancreatitis", "Gastrointestinal Bleeding", "Ischemic Stroke",
          "Cardiological Medicine", "Cardiology", "Cardiologist", "Heart", "Cardiovascular System", "Heart Diseases", "Cardiovascular Diseases",
          "Cardiovascular Health", "Heart Health", "Cardiac Disorders", "Heart Conditions", "Cardiac Care", "Heart Examination",
          "Cardiac Imaging", "Cardiac Tests", "Heart Monitoring", "Cardiac Treatment", "Cardiac Interventions", "Heart Surgery",
          "Cardiac Rehabilitation", "Echocardiography", "Electrocardiogram (ECG or EKG)", "Stress Test", "Holter Monitor", "Cardiac Catheterization",
          "Angiography", "Coronary Angioplasty", "Coronary Stenting", "Cardioversion", "Pacemaker", "Implantable Cardioverter-Defibrillator (ICD)",
          "Heart Transplant", "Heart Failure", "Coronary Artery Disease (CAD)", "Myocardial Infarction", "Angina Pectoris", "Arrhythmia",
          "Atrial Fibrillation", "Bradycardia", "Tachycardia", "Valvular Heart Disease", "Mitral Valve Prolapse", "Hypertension", "Hypotension",
          "Cardiomyopathy", "Dilated Cardiomyopathy", "Hypertrophic Cardiomyopathy", "Restrictive Cardiomyopathy", "Heart Murmur", "Endocarditis",
          "Pericarditis", "Cardiac Tamponade", "Aortic Dissection", "Congenital Heart Disease", "Congestive Heart Failure", "Cor Pulmonale",
          "Cyanotic Heart Disease", "Pulmonary Hypertension", "Ischemic Heart Disease", "Myocarditis", "Rheumatic Heart Disease", "Atherosclerosis",
          "Cholesterol", "Lipid Profile", "Cardiovascular Risk Factors", "Smoking Cessation", "Diabetes Management", "Exercise", "Healthy Diet",
          "Obesity", "Stress Management", "Medications", "Blood Thinners", "Beta Blockers", "Calcium Channel Blockers", "ACE Inhibitors", "ARBs",
          "Diuretics", "Vasodilators", "Statins", "Antiplatelet Agents", "Nitroglycerin", "Cardiovascular Rehabilitation", "Cardiac Health Education",
          "Preventive Cardiology", "Cardiovascular Research", "Cardiac Ultrasound", "Transesophageal Echocardiogram (TEE)", "Nuclear Stress Test",
          "Coronary Calcium Scan", "Cardiac CT Angiography", "Cardiac MRI", "Electrophysiology Study (EPS)", "Holter Monitor", "Loop Recorder",
          "Cardiac Event Monitor", "Exercise Stress Test", "Echocardiogram", "Stress Echocardiogram", "Dobutamine Stress Echocardiogram",
          "Radionuclide Imaging", "Coronary Angiogram", "Cardiac Catheterization", "Right Heart Catheterization", "Fractional Flow Reserve (FFR)",
          "Intravascular Ultrasound (IVUS)", "Optical Coherence Tomography (OCT)", "Angioplasty", "Coronary Stent", "Atherectomy", "Rotablation",
          "Thrombectomy", "Pacemaker Implantation", "Implantable Cardioverter-Defibrillator (ICD) Implantation", "Cardiac Resynchronization Therapy (CRT)",
          "Heart Valve Repair", "Heart Valve Replacement", "Mitral Valve Repair", "Mitral Valve Replacement", "Aortic Valve Repair",
          "Aortic Valve Replacement", "Transcatheter Aortic Valve Replacement (TAVR)", "Left Ventricular Assist Device (LVAD)",
          "Heart Transplantation", "Cardiac Rehabilitation", "Cardiac Medications", "Aspirin", "Clopidogrel", "Warfarin", "Rivaroxaban", "Apixaban",
          "Eliquis", "Dabigatran", "Pradaxa", "Metoprolol", "Atenolol", "Lisinopril", "Enalapril", "Losartan", "Valsartan", "Furosemide",
          "Hydrochlorothiazide", "Statins", "Atorvastatin", "Rosuvastatin", "Ezetimibe", "Niacin", "Aspirin", "Clopidogrel", "Nitroglycerin",
          "Isosorbide Dinitrate", "Isosorbide Mononitrate", "Amlodipine", "Verapamil", "Diltiazem", "Ranolazine", "Digoxin", "Amiodarone", "Sotalol",
          "Beta Blockers", "ACE Inhibitors", "ARBs", "Diuretics", "Hydralazine", "Ivabradine", "Sacubitril/Valsartan", "Warfarin", "Rivarox",
          "Visceral Surgery", "Abdominal Surgery", "Gastrointestinal Surgery", "Abdominal Organs", "Digestive System", "Abdominal Cavity",
          "Surgical Procedures", "Laparoscopic Surgery", "Open Surgery", "Minimally Invasive Surgery", "Intra-abdominal Surgery", "Hernia Repair",
          "Gallbladder Surgery", "Appendectomy", "Colectomy", "Gastrectomy", "Esophagectomy", "Whipple Procedure", "Bowel Resection",
          "Bariatric Surgery", "Colorectal Surgery", "Hepatobiliary Surgery", "Liver Surgery", "Pancreatic Surgery", "Spleen Surgery",
          "Gastric Bypass", "Laparoscopic Cholecystectomy", "Laparoscopic Appendectomy", "Laparoscopic Colectomy", "Laparoscopic Gastrectomy",
          "Laparoscopic Hernia Repair", "Endoscopy", "Endoscopic Procedures", "Gastroscopy", "Colonoscopy", "Esophagoscopy", "Endoscopic Ultrasound (EUS)",
          "Endoscopic Retrograde Cholangiopancreatography (ERCP)", "Gastrointestinal Endoscopy", "Laparoscopic Gastric Bypass",
          "Laparoscopic Sleeve Gastrectomy", "Laparoscopic Gastric Banding", "Laparoscopic Bowel Resection", "Laparoscopic Liver Resection",
          "Laparoscopic Pancreatic Surgery", "Laparoscopic Splenectomy", "Laparoscopic Hernia Repair", "Herniorrhaphy", "Hernioplasty",
          "Inguinal Hernia Repair", "Femoral Hernia Repair", "Incisional Hernia Repair", "Umbilical Hernia Repair", "Hiatal Hernia Repair",
          "Biliary Surgery", "Choledocholithiasis", "Cholecystitis", "Cholangitis", "Gallstones", "Common Bile Duct Exploration",
          "Cholecystectomy", "Hepatic Surgery", "Liver Resection", "Liver Biopsy", "Liver Transplantation", "Pancreatic Surgery",
          "Pancreaticoduodenectomy", "Pancreatic Biopsy", "Spleen Surgery", "Splenectomy", "Splenorrhaphy", "Gastric Surgery",
          "Gastric Cancer Surgery", "Gastrectomy", "Gastrojejunostomy", "Esophageal Surgery", "Esophageal Cancer Surgery",
          "Esophagectomy", "Esophagostomy", "Esophagogastroduodenoscopy (EGD)", "Whipple Procedure", "Colorectal Surgery",
          "Colon Resection", "Rectal Resection", "Hemicolectomy", "Total Colectomy", "Proctectomy", "Low Anterior Resection",
          "Abdominoperineal Resection", "Bowel Obstruction", "Colostomy", "Ileostomy", "Anastomosis", "Gastrointestinal Bleeding",
          "Gastric Ulcers", "Colon Polyps", "Diverticulitis", "Crohn's Disease", "Ulcerative Colitis", "Colorectal Cancer",
          "Inflammatory Bowel Disease", "Surgical Complications", "Surgical Site Infection", "Wound Dehiscence", "Hernia Recurrence",
          "Anastomotic Leak", "Bowel Perforation", "Postoperative Bleeding", "Visceral Trauma", "Visceral Injuries", "Trauma Surgery",
          "Emergency Surgery", "Abdominal Trauma", "Hollow Organ Perforation", "Visceral Tumors", "Gastrointestinal Tumors", "Liver Tumors",
          "Pancreatic Tumors", "Esophageal Tumors", "Colorectal Tumors", "Visceral Pain", "Postoperative Pain", "Gastrointestinal Motility Disorders",
          "Functional Gastrointestinal Disorders", "Visceral Surgeon", "Digestive Surgeon", "Gastrointestinal Surgeon", "Hepatobiliary Surgeon",
          "Liver Surgeon", "Pancreatic Surgeon", "Spleen Surgeon", "Bariatric Surgeon", "Colorectal Surgeon", "Esophageal Surgeon",
          "Gastric Surgeon", "Laparoscopic Surgeon", "Endoscopic Surgeon", "Surgical Oncologist", "Minimally Invasive Surgeon",
          "Surgical Techniques", "Surgical Instruments", "Surgical Approaches", "Surgical Training",
          "Esoterik", "Occultism", "Spirituality", "Mysticism", "Metaphysics", "Hidden Knowledge", "Secret Wisdom", "Alternative Beliefs",
          "Inner Truth", "Ancient Wisdom", "Esotericism", "Esoteric Knowledge", "Transcendence", "Spiritual Enlightenment",
          "Mystical Experience", "Occult Practices", "Symbolism", "Inner Transformation", "Higher Consciousness", "Spiritual Growth",
          "Intuition", "Paranormal Phenomena", "Spiritual Healing", "Energy Healing", "Chakras", "Auras", "Astrology", "Numerology",
          "Tarot", "Divination", "Alchemy", "Hermeticism", "Kabbalah", "Yoga", "Meditation", "Astral Projection", "Lucid Dreaming",
          "Spiritual Guides", "Channeling", "Mediumship", "Past Life Regression", "Akashic Records", "Crystal Healing", "Candle Magic",
          "Herbalism", "Wicca", "Paganism", "Shamanism", "Native American Spirituality", "Eastern Mysticism", "Chakras", "Kundalini",
          "Reiki", "Qi Gong", "Tantra", "Esoteric Philosophy", "Esoteric Literature", "Gnostic Texts", "Secret Societies", "Freemasonry",
          "Rosicrucianism", "Theosophy", "Anthroposophy", "New Age", "Consciousness Exploration", "Synchronicity", "Law of Attraction",
          "Spiritual Symbols", "Inner Alchemy", "Inner Light", "Esoteric Teachings", "Spiritual Practices", "Esoteric Art",
          "Intuitive Wisdom", "Holistic Perspective", "Energetic Balance", "Universal Consciousness", "Unity of All", "Interconnectedness",
          "Spiritual Quest", "Divine Wisdom", "Inner Harmony", "Soul Journey", "Sacred Geometry", "Higher Self", "Awakening", "Divine Love",
          "Inner Peace", "Inner Guidance", "Esoteric Traditions", "Esoteric Symbols", "Inner Knowledge", "Expanded Awareness",
          "Self-Realization", "Esoteric Literature", "Occult Literature", "Esoteric Community", "Esoteric Philosophy", "Esoteric Interpretation",
          "Spiritual Exploration", "Esoteric Practices", "Divine Mysteries", "Higher Realms", "Universal Laws", "Esoteric Healing",
          "Transformational Journey", "Inner Universe", "Transpersonal Experience", "Cosmic Connection", "Esoteric Wisdom Traditions",
          "Divine Connection", "Higher Dimensions", "Esoteric Wisdom Teachings",
          "Nutrients", "Diet", "Food Groups", "Macronutrients", "Micronutrients", "Vitamins", "Minerals", "Protein", "Carbohydrates",
          "Fats", "Fiber", "Calories", "Metabolism", "Balanced Diet", "Dietary Guidelines", "Healthy Eating", "Nutritional Value",
          "Nutrient Absorption", "Nutrient Deficiency", "Nutrient Supplements", "Food Pyramid", "Portion Control", "Meal Planning",
          "Nutritional Labels", "Recommended Daily Allowance (RDA)", "Water Intake", "Hydration", "Antioxidants", "Omega-3 Fatty Acids",
          "Probiotics", "Prebiotics", "Superfoods", "Organic Food", "GMOs (Genetically Modified Organisms)", "Food Additives",
          "Food Allergies", "Food Sensitivities", "Food Intolerances", "Food Safety", "Nutritional Assessment", "Dietitian", "Nutritionist",
          "Dietary Patterns", "Mediterranean Diet", "Vegan Diet", "Vegetarian Diet", "Paleo Diet", "Keto Diet", "Gluten-Free Diet",
          "Low-Carb Diet", "Low-Fat Diet", "Fad Diets", "Weight Management", "Obesity", "Body Mass Index (BMI)", "Caloric Restriction",
          "Intermittent Fasting", "Nutritional Counseling", "Nutritional Education", "Eating Disorders", "Anorexia Nervosa",
          "Bulimia Nervosa", "Binge Eating Disorder", "Food Psychology", "Mindful Eating", "Emotional Eating", "Food Cravings",
          "Sugar Addiction", "Nutritional Supplements", "Multivitamins", "Herbal Supplements", "Sports Nutrition", "Diet and Exercise",
          "Nutritional Research", "Nutritional Epidemiology", "Public Health Nutrition", "Nutritional Guidelines", "Child Nutrition",
          "Teenage Nutrition", "Maternal Nutrition", "Elderly Nutrition", "Malnutrition", "Undernutrition", "Overnutrition",
          "Nutritional Diseases", "Diabetes Management", "Heart-Healthy Diet", "Cancer Prevention Diet", "Osteoporosis Prevention",
          "Nutritional Biochemistry", "Food Processing", "Food Storage", "Cooking Methods", "Nutritional Cooking", "Food and Culture",
          "Sustainable Nutrition", "Food Security", "Nutritional Policy", "Dietary Restrictions", "Nutritional Supplements Safety",
          "Pregnancy", "Pregnant", "Maternity", "Expecting", "Prenatal Care", "Antenatal Care", "Fetal Development", "Pregnancy Symptoms",
          "Maternal Health", "Fertility", "Conception", "Ovulation", "Implantation", "Embryo", "Fetus", "Ultrasound", "Pregnancy Test",
          "Gestational Age", "Due Date", "Obstetrics", "Obstetrician", "Midwife", "Doula", "Pregnancy Complications", "High-Risk Pregnancy",
          "Preeclampsia", "Gestational Diabetes", "Ectopic Pregnancy", "Miscarriage", "Stillbirth", "Preterm Birth", "Labor", "Childbirth",
          "Delivery", "Cesarean Section", "Vaginal Birth", "Labor Contractions", "Birth Plan", "Natural Childbirth", "Water Birth", "Home Birth",
          "Postpartum", "Postpartum Depression", "Breastfeeding", "Infant Care", "Maternal Nutrition", "Pregnancy Diet", "Pregnancy Weight Gain",
          "Prenatal Vitamins", "Morning Sickness", "Cravings", "Pregnancy Exercises", "Prenatal Yoga", "Pregnancy Classes", "Baby Bump",
          "Maternity Clothes", "Pregnancy Books", "Baby Shower", "Nursery", "Pregnancy Apps", "Pregnancy Calendar", "Pregnancy Apps",
          "Fetal Monitoring", "Amniocentesis", "Chorionic Villus Sampling (CVS)", "Fetal Ultrasound", "Pregnancy Check-ups", "Multiple Pregnancy",
          "Twins", "Triplets", "Quadruplets", "Pregnancy Nutrition", "Pregnancy Hormones", "Hormonal Changes", "Pregnancy Discomforts",
          "Pregnancy Health Tips", "Pregnancy Stages", "First Trimester", "Second Trimester", "Third Trimester", "Baby Development",
          "Pregnancy Test Accuracy", "Maternal Bonding", "Pregnancy Support", "Baby Names", "Baby Registry", "Newborn Essentials",
          "Maternity Leave", "Pregnancy Health Risks", "Teen Pregnancy", "Advanced Maternal Age", "Pregnancy and Work", "Pregnancy Rights",
          "Pregnancy Planning", "Pregnancy After Miscarriage", "Pregnancy After 35", "Pregnancy After 40", "Pregnancy Myths", "Pregnancy Facts",
          "Pregnancy Education", "Pregnancy Apps", "Pregnancy Calendar", "Fetal Development", "Pregnancy Diet", "Pregnancy Weight Gain",
          "Pregnancy Exercises", "Pregnancy Classes", "Fetal Monitoring", "Amniocentesis", "Chorionic Villus Sampling (CVS)", "Fetal Ultrasound",
          "Pregnancy Check-ups", "Multiple Pregnancy", "Twins", "Triplets", "Quadruplets", "Pregnancy Nutrition", "Pregnancy Hormones",
          "Hormonal Changes", "Pregnancy Discomforts", "Pregnancy Health Tips", "Pregnancy Stages", "First Trimester", "Second Trimester",
          "Third Trimester", "Baby Development", "Pregnancy Test Accuracy", "Maternal Bonding", "Pregnancy Support", "Baby Names", "Baby Registry",
          "Newborn Essentials", "Maternity Leave", "Pregnancy Health Risks", "Teen Pregnancy", "Advanced Maternal Age", "Pregnancy and Work",
          "Pregnancy Rights", "Pregnancy Planning", "Pregnancy After Miscarriage", "Pregnancy After 35", "Pregnancy After 40", "Pregnancy Myths",
          "Pregnancy Facts", "Pregnancy Education",
          "Tobacco", "Smoking", "Cigarettes", "Nicotine", "Tobacco Industry", "Tobacco Control", "Tobacco Use", "Tobacco Products",
          "Smoking Addiction", "Secondhand Smoke", "Smoking Cessation", "Tobacco Health Effects", "Lung Cancer", "Heart Disease",
          "Respiratory Diseases", "Oral Cancer", "Throat Cancer", "Smoking and Pregnancy", "Tobacco and Youth", "Tobacco Regulations",
          "Tobacco Taxes", "Anti-Smoking Campaigns", "Smoke-Free Policies", "Tobacco Advertising", "Tobacco Marketing",
          "Tobacco Addiction Treatment", "Quitting Smoking", "Smokeless Tobacco", "Electronic Cigarettes", "Vaping", "Hookah Smoking",
          "Tobacco and Public Health", "Tobacco-related Diseases", "Tobacco-related Mortality", "Tobacco Control Programs",
          "Tobacco-Free Initiatives", "Tobacco Education", "Tobacco-Free Generation", "Tobacco Prevention", "Tobacco Harm Reduction",
          "Tobacco Use Surveillance", "Tobacco Policy Advocacy", "Tobacco-Free Communities", "Tobacco Awareness",
          "Tobacco and Youth Smoking Prevention", "Tobacco Use Reduction", "Tobacco-Free Workplace", "Tobacco and Social Impact",
          "Tobacco and Environmental Impact", "Tobacco-Free Schools", "Tobacco Cessation Programs", "Tobacco Control Measures",
          "Tobacco Use Prevention", "Tobacco-Free Advocacy", "Tobacco and Health Disparities", "Tobacco-related Illnesses",
          "Tobacco and Cancer Risk", "Tobacco and Heart Health", "Tobacco and Lung Health", "Tobacco and Oral Health", "Tobacco and Mental Health",
          "Tobacco and Substance Abuse", "Tobacco-related Policies", "Tobacco Research", "Tobacco Epidemiology", "Tobacco Surveys",
          "Tobacco Statistics", "Tobacco Prevention Strategies", "Tobacco Use Reduction Initiatives", "Tobacco-Free Legislation",
          "Tobacco-Free Advocacy Groups", "Tobacco Control Organizations", "Tobacco-Free Campaigns", "Tobacco-Free Initiatives",
          "Tobacco and Health Education", "Tobacco and Health Promotion", "Tobacco and Health Awareness"]





def main(topics):
    print('number of key words before deduplication:', len(topics))
    topics = list(dict.fromkeys(topics))
    print('number of key words after deduplication:', len(topics))

    df = pd.DataFrame(columns=['category_id','text_id','venue','data-source','url','tags','text'])
    for i in topics:
        try:
            item = wikipedia.page(i)
            title = item.title
            row = pd.DataFrame({'category_id': 'popular_science',
                                'text_id':'Wikipedia'+title,
                                'venue':'',
                                'data-source':'Wikipedia',
                                'url':'https://en.wikipedia.org/wiki/'+ title,
                                'tags': '',
                                'text':[item.content]})
            df = pd.concat([df, row], ignore_index=True)
            df = df.replace(r'\n', ' ', regex=True)
            df['text'] = df['text'].str.replace('=', '')
            df['text'] = re.sub('[^a-zA-Z0-9 \n\.]', '', df['text'].str)



        except Exception as e:
            print("Exception", e)
    print(df.shape[0])
    df.to_csv('data/popscience_wikipedia-text_2023-10-07.csv', index=False)

if __name__ == '__main__':
    main(topics)
